import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased pb-14`}
      >
        <div className="w-full border-b border-amber-300/70 bg-amber-50 text-amber-900 text-xs md:text-sm">
          <div className="mx-auto max-w-5xl px-3 py-2 text-center">
            Limited demo: conference FAQs only. No citations, no private systems. <a className="underline hover:no-underline" href="/demo-info">Learn more</a>.
          </div>
        </div>
        {children}
  <Analytics />
        <footer className="fixed inset-x-0 bottom-0 z-50 border-t border-neutral-200/70 bg-white/80 backdrop-blur supports-[backdrop-filter]:bg-white/60">
          <div className="mx-auto max-w-5xl px-3 py-2 text-center text-[11px] md:text-xs text-neutral-500">
            Demonstration by Arkand AI (Woodworth Group LLC). For internal evaluation only. Content limited.
          </div>
        </footer>
      </body>
    </html>
  );
}
